name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  jvm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'corretto'

    # The Android SDK is required to build the project, even if we are not running Android tests.
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Verify README generation
      uses: momentohq/standards-and-practices/github-actions/oss-readme-template@gh-actions-v2
      with:
        project_status: incubating
        project_stability: alpha
        project_type: sdk
        sdk_language: Kotlin
        dev_docs_slug: kotlin

    - name: Build and test project
      uses: gradle/gradle-build-action@v2.11.1
      with:
        arguments: clean build -x jvmTest -x testDebugUnitTest -x testReleaseUnitTest
